#!/usr/bin/env node

import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const BANNER = `
╔═══════════════════════════════════════════════════════════╗
║           Agent Switchboard - Local Control Plane          ║
╚═══════════════════════════════════════════════════════════╝
`;

const ENV_TEMPLATE = `# Agent Switchboard Configuration
# Generated by: npx agent-switchboard init

# Server port
PORT=5000

# Session secret (generate a strong random string for production)
SESSION_SECRET=change-me-in-production

# Database path (relative to project root)
DATABASE_PATH=./data/switchboard.db

# Sandbox directory for agent filesystem operations
SANDBOX_PATH=./sandbox
`;

const GITIGNORE_TEMPLATE = `# Agent Switchboard
data/
sandbox/
*.db
.env
node_modules/
`;

function init(targetDir: string) {
  console.log(BANNER);
  console.log('Initializing Agent Switchboard in:', targetDir);
  console.log('');

  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
  }

  const sandboxDir = join(targetDir, 'sandbox');
  if (!existsSync(sandboxDir)) {
    mkdirSync(sandboxDir, { recursive: true });
    console.log('  Created ./sandbox directory');
  }

  const dataDir = join(targetDir, 'data');
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
    console.log('  Created ./data directory');
  }

  const envPath = join(targetDir, '.env');
  if (!existsSync(envPath)) {
    writeFileSync(envPath, ENV_TEMPLATE);
    console.log('  Created .env file');
  } else {
    console.log('  .env already exists, skipping');
  }

  const gitignorePath = join(targetDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, GITIGNORE_TEMPLATE);
    console.log('  Created .gitignore file');
  }

  console.log('');
  console.log('Setup complete!');
  console.log('');
  console.log('Next steps:');
  console.log('  1. Review and update .env with your configuration');
  console.log('  2. Clone the Agent Switchboard repository');
  console.log('  3. Run: npm install');
  console.log('  4. Run: npm run dev (development) or npm start (production)');
  console.log('');
  console.log('Default admin credentials: admin / admin123');
  console.log('');
  console.log('Documentation: https://github.com/your-org/agent-switchboard');
}

function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  switch (command) {
    case 'init':
      const targetDir = args[1] || process.cwd();
      init(targetDir);
      break;
    case '--version':
    case '-v':
      console.log('agent-switchboard v0.1.0');
      break;
    case '--help':
    case '-h':
    default:
      console.log(BANNER);
      console.log('Usage: npx agent-switchboard <command>');
      console.log('');
      console.log('Commands:');
      console.log('  init [dir]    Initialize a new Agent Switchboard project');
      console.log('  --version     Show version');
      console.log('  --help        Show this help');
      break;
  }
}

main();
